### ISSUE TITLE
GUI only shows 1 minion

### ISSUE THREAD

**Issue by lordfolken** [erwindon/SaltGUI#231] opened 2019-05-27 15:40 UTC
**Describe the bug**
Minion and Key tab only show one entry when clicked. 

**To Reproduce**
1. browse to saltgui
2. Click on tab minions or keys

**Expected behavior**
See all the keys / minion as in the output of salt-key -L 
**Screenshots**
![image](https://user-images.githubusercontent.com/407371/58470348-c89b7780-8141-11e9-9594-3e8220981cce.png)
**Additional context**
I installed the saltgui with the following saltstate: https://github.com/lordfolken/saltgui-formula

**Comment by erwindon** [comment] 2019-05-27 16:21
@lordfolken 
Unfortunatelly, I cannot reproduce the reported problem.
Did you use any previous version of SaltGUI before? (to eliminate cache problems)
Is there any error message in the web browser console?

**Comment by lordfolken** [comment] 2019-05-28 10:02
I think its trying to load the fingerprint or the os version (both keys and minion) have the same issue. This seems to timeout after a very long time, and then actually shows the second node.

**Comment by lordfolken** [comment] 2019-05-28 10:07
Browser debugger entries
Page.js:464:1
TypeError: element is null
DropDown.js:13:1
TypeError: job.Running is undefined
Page.js:464:1

**Comment by lordfolken** [comment] 2019-05-28 10:20
Packages:

ii  salt-api                             2019.2.0+ds-1
ii  salt-common                          2019.2.0+ds-1
ii  salt-master                          2019.2.0+ds-1
ii  salt-minion                          2019.2.0+ds-1
ii  salt-ssh                             2019.2.0+ds-1

salt version: salt 2019.2.0 (Fluorine)

**Comment by lordfolken** [comment] 2019-05-28 10:21
both browser and gui are reinstalled on two seperate systems. I have the same behaviour on both.

**Comment by erwindon** [comment] 2019-05-29 00:28
The browser debugger entries provide a clue.
For some reason, there is no useful information returned from `runner.jobs.active`.
That is a bit strange, but hey, it happens.
The bad thing is that SaltGUI did not test that.
I've now added a small check for that.
Can you retry?

Would you mind sharing the output of the command `salt-run jobs.active`?
feel free to redact minion names, commands, parameters, etc.

**Comment by erwindon** [comment] 2019-05-29 07:07
Unfortunately, the previous observation was not the actual problem.
The problem is that SaltGUI uses the minion names as HTML id-s.
When minion names contain a "." then the problem occurs.
I have reproduced that here.
This will be fixed this evening!

**Comment by erwindon** [comment] 2019-05-29 20:08
@lordfolken 
I've updated SaltGUI to use a simple encoding scheme to derived HTML-IDs from MINION-IDs.
A test with "foo.bar" was positive on all screens.
I've committed the fix on the master branch.
Can you do a quick test and tell me/us whether the fix is sufficient? thx!

**Comment by lordfolken** [comment] 2019-05-30 07:40
This fixes the issue and i can see now all my minions and keys. :) Thank you very much for your efforts.

**Closed** 2019-05-30 07:40 UTC
Labels: HIGH PRIORITY, bug, work-in-progress
