### ISSUE TITLE
Running salt with a MySQL backend will break SaltGui jobs display

### ISSUE THREAD

**Issue by xzenor** [erwindon/SaltGUI#399] opened 2021-11-16 12:01 UTC
**Describe the bug**
Running salt with a MySQL backend will break SaltGui jobs display. the jobs show up perfectly fine on the commandline.

**To Reproduce**
Steps to reproduce the behaviour:
Configure your salt-master to use MySQL as a job cache.
make sure to create the proper tables (see salt documentation).
Run a few jobs.

**Expected behaviour**
SaltGUI giving the same output as `salt-run jobs.lookup_jid JOB-ID`

**Screenshots**
![image](https://user-images.githubusercontent.com/15305998/141981158-f0214c11-5dd5-4114-8d1b-04f61e658622.png)

**Additional context**
I've been struggling with redis as well so it might be a generic backend thing and not just a problem with mysql.

**Comment by erwindon** [comment] 2021-11-16 12:53
Showing a negative number of responses is always bad!
It will take a few days before I can set-up the required system to reproduce this.
Instead, can you just steal the JSON response that was returned by the `jobs.list_job` call and send it over?

FYI: Displaying the job information requires 2 api-calls: `jobs.list_job` for the details and `jobs.active` to see whether it is still running. (and every one minute, "stats" is called by the application to detect session end).

**Comment by xzenor** [comment] 2021-11-16 13:08
Sure thing.
This is the commandline output.
`$ salt-run jobs.list_job 20211116114342060929 --out=json`
```json
{
    "jid": "20211116114342060929",
    "Function": "test.ping",
    "Arguments": [],
    "Target": "*",
    "Target-type": "glob",
    "User": "root",
    "StartTime": "2021, Nov 16 11:43:42.060929",
    "Result": {
        "server-tst01.REDACTED": {
            "cmd": "_return",
            "id": "server-tst01.REDACTED",
            "success": true,
            "return": true,
            "retcode": 0,
            "jid": "20211116114342060929",
            "fun": "test.ping",
            "fun_args": [],
            "_stamp": "2021-11-16T11:43:42.305608"
        },
        "server-tst02.REDACTED": {
            "cmd": "_return",
            "id": "server-tst02.REDACTED",
            "success": true,
            "return": true,
            "retcode": 0,
            "jid": "20211116114342060929",
            "fun": "test.ping",
            "fun_args": [],
            "_stamp": "2021-11-16T11:43:42.365949"
        },
        "server-mgt01.REDACTED": {
            "cmd": "_return",
            "id": "server-mgt01.REDACTED",
            "success": true,
            "return": true,
            "retcode": 0,
            "jid": "20211116114342060929",
            "fun": "test.ping",
            "fun_args": [],
            "_stamp": "2021-11-16T11:43:42.483357"
        }
    }
}
[INFO    ] Runner completed: 20211116125620672471
```
`jobs.active` just gives me the time it took to give 0 results, because there are no active jobs at the moment.

Let me know if I can try some other stuff or provide more data.

**Comment by xzenor** [comment] 2021-11-16 13:16
Well it's obvious why it fails I guess... The json output is completely different it seems.
For comparison, below is the output of the same command **with local jobcache**

`# salt-run jobs.list_job 20211116131018012776 --out=json`
```json
{
    "jid": "20211116131018012776",
    "Function": "test.ping",
    "Arguments": [],
    "Target": "*",
    "Target-type": "glob",
    "User": "root",
    "Minions": [
        "server-mgt01.REDACTED",
        "server-tst01.REDACTED",
        "server-tst02.REDACTED"
    ],
    "StartTime": "2021, Nov 16 13:10:18.012776",
    "Result": {
        "server-tst01.REDACTED": {
            "return": true,
            "retcode": 0,
            "success": true
        },
        "server-tst02.REDACTED": {
            "return": true,
            "retcode": 0,
            "success": true
        },
        "server-mgt01.REDACTED": {
            "return": true,
            "retcode": 0,
            "success": true
        }
    }
}
[INFO    ] Runner completed: 20211116131204988971
```

the one **with** mysql backend is almost twice as long..

**Comment by erwindon** [comment] 2021-11-16 15:22
In this case the missing "Minions" clause gives the funny result.
I'll try to update SaltGUI to show less confusing results.
But without the minions-list, it is not possible to know how many results are expected. previously, the number of "no responses" was based on the difference between the number of Minions-keys and the number of Result-keys.

Feel free to ask support for the "Minions" information block in the Salt issues list: https://github.com/saltstack/salt/issues. It might be a missing feature or it may just be a simple bug.

I'll change SaltGUI now to handle both situations.

**Comment by erwindon** [comment] 2021-11-16 16:27
recreated the issue:
![afbeelding](https://user-images.githubusercontent.com/3663742/142025152-25ec3a0c-837a-48dd-8dcf-a95531548770.png)

**Comment by erwindon** [comment] 2021-11-16 16:31
for some reason, SaltGUI assumes `["WHEEL"]` as the list of keys when the "Minions" block is absent. so I must test any solution with "runners" and "wheel" jobs as well.

**Comment by xzenor** [comment] 2021-11-16 18:21
Nice. So that's confirmed.. It sounds like a lot of work. It's probably worth waiting for a response on my salt ticket. This seems like a salt issue and not a SaltGUI issue. If they fix it, you don't have to.

**Comment by erwindon** [comment] 2021-11-16 19:29
The assumption for `["WHEEL"]` comes from running WHEEL (and/or RUNNERS) jobs via the salt job system. those do not have a list of minions to act on. I've changed (not committed yet) it so that the assumption is only made for WHEEL and RUNNERS commands. for any other command, we'll take the list of minions from the `Result` part of the answer. That is just a handful of JS lines extra.

A few small downsides remain. in the traditional system the screen shows all targetted minions. with additional options in a dropdown menu to cancel/signal/kill/getinfo on the job on a specific minion. but now only the minions that have returned results are shown. the similar per-job menu can still work. and when you navigate too quickly too the job and no answers are received yet, it says "No minions matched the target. No command was sent, no jid was assigned. ERROR: No return received".
But at least you can see the returned values.

**Comment by xzenor** [comment] 2021-11-16 19:36
So, if they fix it in salt itself (if they do consider it a bug), would SaltGUI automatically start reading the Minion block again?

**Comment by erwindon** [comment] 2021-11-16 19:49
> So, if they fix it in salt itself (if they do consider it a bug), would SaltGUI automatically start reading the Minion block again?

yes

**Comment by erwindon** [comment] 2021-11-16 20:00
The solution was simple. But it needed an explanation so that the user is aware that it is applied. So the result is:
![afbeelding](https://user-images.githubusercontent.com/3663742/142055881-fae1dc2f-c1aa-40b3-a54b-dad2d1589239.png)

(obviously, in the traditional case, the warning is not shown)

The warning text is chosen to be universal; it does not speculate on the reason why that information is missing.

You can try the alpha-version yourself on branch `nominionsinresult`.

**Comment by xzenor** [comment] 2021-11-16 22:29
You're really fast.
Seems to be working! It's a big ugly red bar of text but at least it works.

**Comment by erwindon** [comment] 2021-11-16 23:36
I doubted the design too. I'll change it to a friendlier version. Main reason for my doubt is that the warning appears always.

this better?
![afbeelding](https://user-images.githubusercontent.com/3663742/142083154-75203e5e-d567-41f6-b98e-52b1b5716c16.png)

**Comment by xzenor** [comment] 2021-11-17 07:42
That's much nicer in my opinion.

**Comment by erwindon** [comment] 2021-11-17 09:34
ok, we'll keep that one.
The code on the branch has already been updated with the new design.
I still have to do more testing since, according to the original code, there were also exceptions for WHEEL and/or RUNNER jobs.

**Closed** 2021-11-20 12:00 UTC
Labels: bug, work-in-progress
