### ISSUE TITLE
Jobs always says "no minions"

### ISSUE THREAD

**Issue by pckroon** [erwindon/SaltGUI#427] opened 2022-03-01 13:40 UTC
Hello hello!
My job page correctly lists all salt jobs, but under the details it lists "no minions" for all jobs. When I "show details" for a specific job, it shows "minion list is missing in the result, thus cannot determine missing output" with the yellow warning symbol. 
It's probably a config issue on my side, but I'm not sure where to look. Any help would be much appreciated!

**Comment by erwindon** [comment] 2022-03-01 14:00
Peter,
The warning icon was added to confirm that this is a known situation.
But as far as I know it is not caused by SaltGUI (you can verify that by looking at a job that was not started from SaltGUI).
The (only) previous observation for this was from a user that uses a database as backing store for the jobs database.
This caused saltstack to 'forget' this data.
See also #399

**Comment by pckroon** [comment] 2022-03-01 14:19
Wow you're fast :)
It's indeed the same (underlying) issue, with the only difference I'm using a pgjsonb returner. That seemed like a good idea at the time, but maybe it isn't?
I'll dig a little bit more, but I think this closes this issue. Thanks for the quick reply!

**Comment by erwindon** [comment] 2022-03-01 14:42
I might contribute to the saltstack issue and cause this information to be stored also in the database.
Can you easily provide the data-model of the database? (e.g. an export with only the table structures)

**Comment by erwindon** [comment] 2022-03-02 02:01
thx, that was exactly what I needed...
I had to choose `postgres` instead of `pgjsonb`, but the effect you described did not occur yet.
did you configure anything else except the returner and its database?
was there any special configuration on the minions?
did the problem occur for recent job data, older job data or both?

note:
I made the changes for #399 based on data supplied by the issue owner and just used that data as simulated response from salt.
That's why this is the first time I set up a salt system like this.

**Comment by pckroon** [comment] 2022-03-02 15:41
> did the problem occur for recent job data, older job data or both?

Both, but it started bothering me recently. 

> was there any special configuration on the minions?

No? Not that I'm aware of, anyway. 

> did you configure anything else except the returner and its database?

There is more config in my master conf, but this is all that seems relevant to the returner and saltgui.
```
root@salt:/etc/salt# grep pgjsonb master
#event_return: [pgjsonb]
master_job_cache: pgjsonb
#return: pgjsonb
returner.pgjsonb.host: '127.0.0.1'
returner.pgjsonb.user: REDACTED
returner.pgjsonb.pass: REDACTED
returner.pgjsonb.db: 'salt'
returner.pgjsonb.port: 5432
returner.pgjsonb.sslmode: 'require'
#returner.pgjsonb.ssl_ca: 
returner.pgjsonb.sslcert: '/etc/salt/pki/tls/certs/localhost.crt'
returner.pgjsonb.sslkey: '/etc/salt/pki/tls/certs/localhost.key'

root@salt:/etc/salt# cat master.d/*
rest_cherrypy:
  port: 8080
  host: 192.168.12.56
  debug: False
  ssl_crt: /etc/salt/pki/tls/certs/localhost.crt
  ssl_key: /etc/salt/pki/tls/certs/localhost.key
  log.error_file: /var/log/salt/api.error
  log.access_file: /var/log/salt/api.access
  collect_stats: False
  app: /srv/SaltGUI/saltgui/index.html
  static: /srv/SaltGUI/saltgui/static
  static_path: /static
saltgui_output_formats: highstate,yaml
saltgui_datetime_fraction_digits: 0
saltgui_preview_grains:
  - "$.fqdn_ip4[0]"
  - productname
```
Let me know if you need more, I'm happy to help :)

**Comment by erwindon** [comment] 2022-03-02 16:16
at least one more person is also using `saltgui_preview_grains` :-)
both returners are commented out here. I assume that we are discussing a case where at least `return: pgjsonb` is set?
otherwise no surprises here, and I'll try to reproduce using `pgjsonb`...

**Comment by pckroon** [comment] 2022-03-03 09:21
Hmmn, I was under the impression `master_job_cache: pgjsonb` was sufficient. New jobs do show up in the database. I'll try uncommenting the `return: pgjsonb` and get back to you.

**Comment by pckroon** [comment] 2022-03-03 10:18
Doesn't seem to help. I can't access the saltgui at the moment (working from home today), but I can show you the following:
```
root@salt:/etc/salt# salt-run config.get return
pgjsonb

root@salt:/etc/salt# salt minion.example.com test.ping --show-jid
jid: 20220303101428641923
minion.example.com:
    True

root@salt:/etc/salt# salt-run jobs.list_job 20220303101428641923 --out=json
{
    "jid": "20220303101428641923",
    "Function": "test.ping",
    "Arguments": [],
    "Target": "unknown-target",
    "Target-type": "list",
    "User": "root",
    "StartTime": "2022, Mar 03 10:14:28.641923",
    "Result": {
        "minion.example.com": {
            "id": "minion.example.com",
            "cmd": "_return",
            "fun": "test.ping",
            "jid": "20220303101428641923",
            "_stamp": "2022-03-03T10:14:28.717171",
            "return": true,
            "retcode": 0,
            "success": true,
            "fun_args": []
        }
    }
}
```
This is with the `return: pgjsonb` in the master conf.

**Comment by erwindon** [comment] 2022-03-03 14:53
Let's not forget that I don't have any experience with non-default returners... :-)

The final example shows that the field `Minions` is not present (and the field `Target` now has a useless value and field `Target-Type` has the wrong value as you implicitly used `glob`; but that is all due to the fact that the parts from the request have been lost.

I think I have enough information, first I'll setup the `pgjsonb` returner and work from there.
That takes a bit of time as I also have a day-job and I'm also a movie-addict...

**Comment by erwindon** [comment] 2022-03-06 10:58
Just adding the `master_job_cache` was enough to reproduce the situation. I did not bother to go to `pgjsonb` after that.

There are a few differences visible:
* `runner`/`wheel` jobs are now also visible in the jobs list. they have a stored `target` field which holds an artificial value (hostname + `_master`).
* when viewing the jobs page, for `runner`/`wheel` jobs show an error because it does not know how to handle the return codes from these. it is visible as `1 failure(undefined)`
* when viewing the jobs page, for the regular jobs `no minions` is show. this is what started this github issue. for `runner`/`wheel` jobs that is actually correct, but maybe also superfluous.
* some of the internally used `runner`/`wheel` commands are not hidden from the jobs lists. the policy in SaltGUI is to hide internally used commands so that the more interesting jobs are visible.

I'll continue improving where possible. but unfortunately that won't fix the original issue. see #428.

**Closed by erwindon** 2022-03-06 10:58 UTC
Labels: question
