### ISSUE TITLE
Error: Internal Server Error

### ISSUE THREAD

**Issue by buffman23** [erwindon/SaltGUI#417] opened 2022-02-02 23:04 UTC
I am getting the message "Error: Internal Server Error" for API requests done through the GUI.

I can make salt-api requests from the command line fine with curl, but when I run the SaltGUI in Firefox, things just say (error) and when I hover it says: status: "500", message: "Internal Server Error". When I try to run a command from the Manual Run page, I get the same Internal Server Error message. On the Issues page, it says it could not retrieve any of the lists.

I also get logged out after 30 or less seconds of being logged in, every time.

OS: CentOS7
Salt version: salt 2016.11.6 (Carbon)
Firefox version: Mozilla Firefox 68.10.0esr

![SaltGUI_Error_1](https://user-images.githubusercontent.com/25783731/152251779-d564c4a4-e4fb-46cd-a5f3-f683d376c948.png)
![SaltGUI_Error_2](https://user-images.githubusercontent.com/25783731/152251781-7ce790f1-788e-43b7-9084-4d649b0fed1d.png)
![SaltGUI_Error_3](https://user-images.githubusercontent.com/25783731/152251783-90cabb0f-8ff6-445f-874a-6d7046a99a97.png)
![SaltGUI_Error_4](https://user-images.githubusercontent.com/25783731/152251785-8b57bbfd-36b2-43f1-9ff4-efb60c3740cc.png)

Any help would be very appreciated!

**Comment by erwindon** [comment] 2022-02-03 10:31
@buffman23
SaltGUI automatically cancels a session when it find that the connection with the salt-api/salt-master is failing. this is a check that is performed every 60 seconds. This is usually due to session timeout, master/api restart or technical difficulties. So that effect is likely not a separate problem.

The salt-api has evolved over the years and with a salt installation of that age, problems are not unexpected.
e.g. SaltGUI may use api functions that are not available in that older version.

I'm really puzzled why you are using such an old version of salt...
And I'm hesitant to support that because I need to change my environment to 2016.11 too.
Is upgrade of salt-master/salt-api to a more recent version feasible?
Otherwise, just write "yes I need 2016.11" in a comment here and I will try to reproduce that situation.

**Comment by erwindon** [comment] 2022-02-03 15:39
(reproducing it will be a bit hard since only the 3xxx versions are available)

**Comment by erwindon** [comment] 2022-02-08 23:30
I was curious enough to try this out anyway.
Found 2016.11.10 in the salt archives and tried it.
my observations:
* I do not see automatic logout
* all regular (="local") salt-api calls fail, so grains/pillars/schedules/beacon operations fail
* all "wheel" and "runner" salt-api calls succeed, so minions/keys/jobs operations work.
* there is no information in the log files

trying curl now...

**Comment by erwindon** [comment] 2022-02-09 00:51
For the automatic logout, It would be helpful when you can peek at the (normally hidden) `Options` screen.
To go there, use ctrl-click on the SaltGUI logo in the top-left corner, the only way to get there.
Does the `session_expire` block provide any useful information?

My session shows:
![afbeelding](https://user-images.githubusercontent.com/3663742/153100641-f1f052df-a272-499b-a1c4-5c4ded1d46d0.png)

**Comment by buffman23** [comment] 2022-02-11 20:43
![SaltGUI_Options](https://user-images.githubusercontent.com/25783731/153667225-e2f61145-e2e2-488e-963c-cad7c1aad409.png)
The page seems to be empty.

I can use a later version of CentOS if it need be.

**Comment by erwindon** [comment] 2022-02-11 22:12
the page is empty because SaltGUI has a problem creating the page, as shown by the error message.
the `replaceAll` function is supported starting from Firefox 77 (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll, you reported your version as Firefox 68).
I've replaced that function with an equivalent alternative.
can you please `git pull` the branch and try again?

**Comment by buffman23** [comment] 2022-02-15 20:54
Oops, I didn't know there was a branch for old salt versions. The application seems to be functioning appropriately now.

![SaltGUI_working](https://user-images.githubusercontent.com/25783731/154147295-d488eec8-6387-48ed-9e92-6e656af96bbf.png)

The only thing is I still get kicked back to the login screen within a minute of being logged in.

here is a pdf print of the hidden options page.
[hidden_options_page.pdf](https://github.com/erwindon/SaltGUI/files/8074553/hidden_options_page.pdf)

**Comment by erwindon** [comment] 2022-02-15 22:37
3 errors are present:

1) a proper icon for Oracle Solaris was missing (the icon is shown as a warning icon). the console windows at the bottom provides enough information for me to know which icon filename I should add. that is done now. the icon looks a bit weird because oracle never bothered to create a logo for this product.

2) the "stats" overview (the right-hand-side of the hidden page) shows an error message. Assuming that the master also has version 2016.11.6, the "/stats" api call should have been supported. On my system, that panel provides some information. Not that it is useful for this problem at hand, but it is unexpected.
can you please re-open that page and show what the tooltips on each of the 2 "(error)" clauses show?

3) you are logged out within a minute of being logged in; and
can you please provide the browser log from the moment you were just logged out?
additionally, can you look at the "Network" tab (instead of "Console") and look for the response of the latest api call "/stats"?
FYI: The "/stats" API call that is used to populate the right-hand-side of the (hidden) Options screen is also used to determine whether the session has become invalid. When that call fails, it is assumed that the login-session is bad and SaltGUI cleans up and returns to the login screen.

**Comment by erwindon** [comment] 2022-02-16 00:44
> Oops, I didn't know there was a branch for old salt versions. 
that branch was created in response to this issue.
any good solution that comes out this will get merged into the main branch.
e.g. the "Oracle Solaris" icon was first added to that branch, tested OK and then moved to the main branch.
(it then automagically disappears from this branch due to a 'rebase' action)

**Comment by erwindon** [comment] 2022-02-22 00:22
does the "logout" problem still occur? or were you able to solve it?

**Comment by erwindon** [comment] 2022-03-02 16:49
I've decided not to continue on this one, because:
* this is a really discouraged setup. no matter how old the the salt-minions are, the salt-master and salt-api should always be up-to-date to prevent most risks for the group of computers that is maintained with that saltstack platform; and
* it is unlikely that other users have a similar setup; and
* also, you are not very responsive.

note that this has no consequences for #421 that you also opened.

**Closed by erwindon** 2022-03-02 16:49 UTC
Labels: enhancement

**Comment by erwindon** [comment] 2022-03-06 12:00
for the record, the following changes were needed to support the old installation:
* [salt-api] use `expr_form` instead of `tgt_type` for salt versions before 2017.x; and
* [firefox] use `replace()` instead of `replaceAll()` (and use `g` flag on the pattern) for firefox versions before 77.
