### ISSUE TITLE
PAM Login not working

### ISSUE THREAD

**Issue by mdtabrezpasha** [erwindon/SaltGUI#514] opened 2023-05-13 16:31 UTC
Hello Everyone,
                         got a problem with my fresh saltgui install. unable to login using pam auth.

![image](https://github.com/erwindon/SaltGUI/assets/50145580/6565fd8f-d517-42de-8368-af7f4293815b)

Any solution?            

**Describe the bug**
Pam Auth not woring on fresh install fo 3006

**Comment by erwindon** [comment] 2023-05-13 16:39
that is not sufficient information to solve the problem...

did you read the warning at the top of the documentation (https://erwindon.github.io/SaltGUI/)?

I'll repeat it here:
> IMPORTANT: since Salt version 3006, it is needed to add configuration option netapi_enable_clients to allow salt-api - and thus SaltGUI - to work. See also [netapi-enable-clients.html](https://docs.saltproject.io/en/3006.0/topics/netapi/netapi-enable-clients.html#netapi-enable-clients). Additionally, any Python packages that the SaltStack installation also depends on, must be installed with salt-pip. This includes authentication plugins such as yubico_client, or execution modules such as boto3_sns.

**Comment by erwindon** [comment] 2023-05-13 16:42
when the problem remains, can you post the relevant parts of the salt-master/salt-api configuration from file `/etc/salt/master`?

**Comment by mdtabrezpasha** [comment] 2023-05-13 17:26
Hi Erwin, I had added the netapi settings as suggested in your documentation during install.

![image](https://github.com/erwindon/SaltGUI/assets/50145580/598e4447-3eb3-42b3-9356-603f792b8e60)


hope these settings are correct.

**Comment by erwindon** [comment] 2023-05-13 21:31
the `external_auth` block looks fine.
the `netapi_enable_clients` block looks fine too. though you have more clients enabled than needed for SaltGUI, but the needed ones are there.
I assume you have the `rest_cherrypy` block properly set-up so that you at least have the login screen, so that one should be ok too.

you configured user `saltadmin` for salt-api, and thus for SaltGUI.
can you login on the Linux level using account `saltadmin`?

**Comment by mdtabrezpasha** [comment] 2023-05-14 06:47
Yes, i am able to login at Linux level

**Comment by erwindon** [comment] 2023-05-14 09:01
I'm afraid I have no more suggestions based on the available information.

If you are sharing the following information, then I can replay the situation and analyze:
* operating system and version (from your screenprint: Ubuntu 22.04.2)
* saltstack version (from your initial info: 3006)
* saltgui version (output from `git rev-parse --short HEAD` while in the `saltgui` git workspace)
* salt configuration (the entire file `/etc/salt/master`; check and mask any sensitive information)

**Comment by ThasianXi** [comment] 2023-05-17 01:18
I had the same issue authenticating to SaltGUI on Ubuntu however, the issue is not present on RHEL 9.x
Add the salt user to the shadow group.  After that, I was able to successfully authenticate to SaltGUI with the pam user I setup in the `/etc/salt/master`

`sudo usermod -aG shadow salt`
Restart `sudo systemctl restart salt-master salt-api`

Source:
[saltstack/salt/issues/64275](https://github.com/saltstack/salt/issues/61770#issue-1164198269)

**Comment by erwindon** [comment] 2023-05-17 07:26
@ThasianXi thx for the additional info! I'll replay this situation.

**Comment by erwindon** [comment] 2023-05-17 21:40
I've replayed this situation with a fresh Ubuntu 22.04.2 and SaltStack 3006.1 and latest SaltGUI.
user could no login into SaltGUI like @mdtabrezpasha reported.
after the `salt` user was made a group member of the `shadow` group, as suggested by @ThasianXi, login is possible.

I'll add the needed commands to the documentation.

**Comment by erwindon** [comment] 2023-05-17 21:55
added to the "quick start" section:
> To successfully use `salt-api` with a default PAM setup, if may be needed to grant read access on `/etc/shadow` to the `salt` user. This is best done using `sudo usermod --append --groups shadow salt`.

@mdtabrezpasha since the symptoms exactly match this situation, I trust this information is helpful and I'm closing this issue.

**Closed** 2023-05-17 21:55 UTC
Labels: help wanted, work-in-progress
